name: Release KamaiZen LSP

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        goos: [linux, darwin, windows]
        arch: [x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Build KamaiZen
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.arch }} go build -o kamaizen${{ matrix.goos == 'windows' && '.exe' || '' }}

      - name: Archive
        run: |
          tar -czvf kamaizen-${{ matrix.os }}-${{ matrix.arch }}.tar.gz kamaizen

      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: kamaizen-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          path: kamaizen-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
