name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x64]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Build
        run: go build -o kamaizen

      - name: Archive
        run: tar -czvf kamaizen-${{ matrix.os }}-${{ matrix.arch }}.tar.gz kamaizen

      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: kamaizen-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
          path: kamaizen-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
